package com.devilopers.guigeek.vins;

public class StaticData {

	public static final String[] appellations = new String[] {
		"Ajaccio",
		"Aloxe-corton",
		"Alsace",
		"Alsace Grand Cru",
		"Anjou",
		"Anjou-coteaux-de-la-loire",
		"Anjou Villages",
		"Anjou Villages Brissac",
		"Arbois",
		"Auxey-duresses",
		"Bandol",
		"Banyuls",
		"Banyuls Grand Cru",
		"Barsac",
		"Bâtard-montrachet",
		"Béarn",
		"Beaujolais",
		"Beaujolais-villages",
		"Beaumes-de-venise",
		"Beaune",
		"Bellet",
		"Bergerac",
		"Bienvenues-bâtard-montrachet",
		"Blagny",
		"Blaye",
		"Bonnes-mares",
		"Bonnezeaux",
		"Bordeaux",
		"Bordeaux Supérieur",
		"Bourgogne",
		"Bourgogne Aligoté",
		"Coteaux-bourguignons",
		"Bourgogne Mousseux",
		"Bourgogne Passe-tout-grains",
		"Bourgueil",
		"Bouzeron",
		"Brouilly",
		"Bugey",
		"Buzet",
		"Cabardès",
		"Cabernet D'Anjou",
		"Cabernet De Saumur",
		"Cadillac",
		"Cahors",
		"Canon-fronsac",
		"Cassis",
		"Cérons",
		"Chablis",
		"Chablis Grand Cru",
		"Chambertin",
		"Chambertin-clos-de-bèze",
		"Chambolle-musigny",
		"Champagne",
		"Chapelle-chambertin",
		"Charlemagne",
		"Charmes-chambertin",
		"Chassagne-montrachet",
		"Château-chalon",
		"Château-grillet",
		"Châteaumeillant",
		"Châteauneuf-du-pape",
		"Châtillon-en-diois",
		"Chénas",
		"Chevalier-montrachet",
		"Cheverny",
		"Chinon",
		"Chiroubles",
		"Chorey-lès-beaune",
		"Clairette De Bellegarde",
		"Clairette De Die",
		"Clairette Du Languedoc",
		"Clos-de-la-roche",
		"Clos-de-tart",
		"Clos-de-vougeot",
		"Clos-des-lambrays",
		"Clos-saint-denis",
		"Collioure",
		"Condrieu",
		"Corbières",
		"Corbières-boutenac",
		"Cornas",
		"Corse",
		"Corton",
		"Corton-charlemagne",
		"Costières-de-nîmes",
		"Côte-de-beaune",
		"Côte-de-beaune-villages",
		"Côte-de-nuits-villages",
		"Côte-de-brouilly",
		"Côte-roannaise",
		"Côte-rôtie",
		"Coteaux-champenois",
		"Coteaux-d'aix-en-provence",
		"Coteaux-de-die",
		"Coteaux-de-l'aubance",
		"Coteaux-de-saumur",
		"Coteaux-du-giennois",
		"Coteaux-du-layon",
		"Coteaux-du-loir",
		"Coteaux-du-lyonnais",
		"Coteaux-du-vendômois",
		"Coteaux-varois-en-provence",
		"Côtes-de-bergerac",
		"Côtes-de-blaye",
		"Côtes-de-bordeaux",
		"Côtes-de-bordeaux-saint-macaire",
		"Côtes-de-bourg",
		"Côtes-de-duras",
		"Côtes-de-montravel",
		"Côtes-de-provence",
		"Côtes-de-toul",
		"Côtes-du-forez",
		"Côtes-du-jura",
		"Côtes-du-marmandais",
		"Côtes-du-rhône",
		"Côtes-du-rhône Villages",
		"Côtes-du-roussillon",
		"Côtes-du-roussillon Villages",
		"Côtes-du-vivarais",
		"Cour-cheverny",
		"Crémant D'Alsace",
		"Crémant De Bordeaux",
		"Crémant De Bourgogne",
		"Crémant De Die",
		"Crémant De Limoux",
		"Crémant De Loire",
		"Crémant Du Jura",
		"Criots-bâtard-montrachet",
		"Crozes-hermitage",
		"Échezeaux",
		"Entre-deux-mers",
		"Faugères",
		"Fiefs-vendéens",
		"Fitou",
		"Fixin",
		"Fleurie",
		"Fronsac",
		"Fronton",
		"Gaillac",
		"Gaillac-premières-côtes",
		"Gevrey-chambertin",
		"Gigondas",
		"Givry",
		"Grands-échezeaux",
		"Graves",
		"Graves-de-vayres",
		"Graves-supérieures",
		"Grignan-les-adhémar",
		"Griotte-chambertin",
		"Haut-médoc",
		"Haut-montravel",
		"Haut-poitou",
		"Hermitage",
		"Irancy",
		"Irouléguy",
		"Jasnières",
		"Juliénas",
		"Jurançon",
		"L'étoile",
		"La-grande-rue",
		"La-romanée",
		"La-tâche",
		"Ladoix",
		"Lalande-de-pomerol",
		"Languedoc",
		"Latricières-chambertin",
		"Les-baux-de-provence",
		"Limoux",
		"Lirac",
		"Listrac-médoc",
		"Loupiac",
		"Luberon",
		"Lussac-saint-émilion",
		"Mâcon",
		"Madiran",
		"Malepère",
		"Maranges",
		"Marcillac",
		"Margaux",
		"Marsannay",
		"Maury",
		"Mazis-chambertin",
		"Mazoyères-chambertin",
		"Médoc",
		"Menetou-salon",
		"Mercurey",
		"Meursault",
		"Minervois",
		"Minervois-la-livinière",
		"Monbazillac",
		"Montagne-saint-émilion",
		"Montagny",
		"Monthélie",
		"Montlouis-sur-loire",
		"Montrachet",
		"Montravel",
		"Morey-saint-denis",
		"Morgon",
		"Moselle",
		"Moulin-à-vent",
		"Moulis",
		"Muscadet",
		"Muscadet-coteaux-de-la-loire",
		"Muscadet-côtes-de-grandlieu",
		"Muscadet-sèvre-et-maine",
		"Muscat De Beaumes-de-Venise",
		"Muscat De Frontignan",
		"Muscat De Lunel",
		"Muscat De Mireval",
		"Muscat De Rivesaltes",
		"Muscat De Saint-Jean-de-Minervois",
		"Muscat Du Cap-Corse",
		"Musigny",
		"Néac",
		"Nuits-saint-georges",
		"Orléans",
		"Orléans-cléry",
		"Pacherenc-du-vic-bilh",
		"Palette",
		"Patrimonio",
		"Pauillac",
		"Pécharmant",
		"Pernand-vergelesses",
		"Pessac-léognan",
		"Petit-chablis",
		"Pierrevert",
		"Pomerol",
		"Pommard",
		"Pouilly-fuissé",
		"Pouilly-fumé",
		"Pouilly-loché",
		"Pouilly-sur-loire",
		"Pouilly-vinzelles",
		"Premières-côtes-de-bordeaux",
		"Puisseguin-saint-émilion",
		"Puligny-montrachet",
		"Quarts-de-chaume",
		"Quincy",
		"Rasteau",
		"Régnié",
		"Reuilly",
		"Richebourg",
		"Rivesaltes",
		"Romanée-conti",
		"Romanée-saint-vivant",
		"Rosé D'Anjou",
		"Rosé De Loire",
		"Rosé Des Riceys",
		"Rosette",
		"Roussette De Savoie",
		"Roussette Du Bugey",
		"Ruchottes-chambertin",
		"Rully",
		"Saint-amour",
		"Saint-aubin",
		"Saint-bris",
		"Saint-chinian",
		"Saint-émilion",
		"Saint-émilion Grand Cru",
		"Saint-estèphe",
		"Saint-georges-saint-émilion",
		"Saint-joseph",
		"Saint-julien",
		"Saint-nicolas-de-bourgueil",
		"Saint-péray",
		"Saint-pourçain",
		"Saint-romain",
		"Saint-véran",
		"Sainte-croix-du-mont",
		"Sainte-foy-bordeaux",
		"Sancerre",
		"Santenay",
		"Saumur",
		"Saumur-champigny",
		"Saussignac",
		"Sauternes",
		"Savennières",
		"Savigny-lès-beaune",
		"Seyssel",
		"Tavel",
		"Touraine",
		"Touraine-noble-joué",
		"Vacqueyras",
		"Valençay",
		"Ventoux",
		"Vin De Savoie",
		"Vinsobres",
		"Viré-clessé",
		"Volnay",
		"Vosne-romanée",
		"Vougeot",
		"Vouvray"
	};
	
	
	public static final String[] cepages = new String[] {
		"Abondant",
		"Abouriou",
		"Admirable de Courtiller",
		"Aglianico",
		"Airén",
		"Albana",
		"Albariño",
		"Aleatico",
		"Alicante-henri-bouschet",
		"Aligoté",
		"Alphonse-lavallée",
		"Altesse",
		"Amigne",
		"Angevine Oberlin",
		"Aramon",
		"Aranel",
		"Arbane",
		"Arbois",
		"Arinarnoa",
		"Arinto",
		"Arriloba",
		"Arrouya",
		"Arvine",
		"Arrufiac",
		"Auxerrois",
		"Baco",
		"Baga",
		"Balochin",
		"Barbaroux",
		"Barbera",
		"Baroque",
		"Bergeron",
		"Bia",
		"Black Hamburg",
		"Blanc Verdan",
		"Bleu de Franconie",
		"Bogazkere",
		"Bombino",
		"Bonarda",
		"Bovale",
		"Bouchet",
		"Bourboulenc",
		"Brachetto",
		"Brunello",
		"Bual",
		"Bezoul el khadem",
		"Cabernet",
		"Cabernet franc",
		"Cabernet-sauvignon",
		"Canaiolo",
		"Cannonau",
		"Carcajolo blanc",
		"Carcajolo noir",
		"Cardinal",
		"Carignan ",
		"Carménère",
		"Carricante",
		"Castellaro",
		"Catarratto",
		"César",
		"Chambourcin",
		"Chancellor",
		"Chardonnay",
		"Chasselas",
		"Chasselas de Jérusalem",
		"Chasselas de Moissac",
		"Chasselas de Thomery",
		"Chatus",
		"Chelois",
		"Chenin",
		"Ciliegiolo",
		"Cinsault",
		"Clairette",
		"Claverie",
		"Clinton",
		"Colombard",
		"Colorino",
		"Corbèse",
		"Cornalin",
		"Cortese",
		"Corvina",
		"Côt",
		"Counoise",
		"Couston",
		"Croatina",
		"Crussin",
		"Czabah",
		"Dabouki",
		"Danube",
		"Dattier de Beyrouth",
		"Dindarella",
		"Diolinoir",
		"Divico",
		"Dobricic",
		"Dolcetto",
		"Donnery",
		"Doukkala",
		"Duras",
		"Durif",
		"Elbling",
		"Emir",
		"Ermitage",
		"Étraire de la Dui",
		"Falanghina",
		"Fendant",
		"Fer Servadou",
		"Feteasca",
		"Fiano",
		"Folle-Blanche",
		"Fragolino",
		"Frankenthal",
		"Frankonia",
		"Frappato di Vittoria",
		"Frankovka",
		"Freisa",
		"Friulano",
		"Frontenac",
		"Furmint",
		"Fumin",
		"Gaglioppo",
		"Gamaret",
		"Gamay",
		"Gamay de Bouze",
		"Gamay de Chaudenay",
		"Gamay Fréaux",
		"Gamza",
		"Ganson",
		"Garganega",
		"Garanoir",
		"Gascon",
		"Genovese",
		"Gewurztraminer",
		"Goldriesling",
		"Gouais",
		"Gouget",
		"Graisse",
		"Gramon",
		"Grassen",
		"Grechetto",
		"Greco",
		"Grenache",
		"Gringet",
		"Grignolino",
		"Grolleau",
		"Groppello bianco",
		"Groppello gentile",
		"Groppello di Mocasina",
		"Groppello di Santo Stefano",
		"Gros colman",
		"Gros manseng",
		"Gros noir des Béni-Abbès",
		"Gros vert",
		"Gutedel",
		"Grüner Veltliner",
		"Hárslevelü",
		"Hibou",
		"Humagne blanche",
		"Humagne rouge",
		"Idéal",
		"Inzolia",
		"Isabelle",
		"Italia",
		"Jacquère",
		"Jacquez",
		"Jaoumet",
		"Johannisberg",
		"Joubertin",
		"Kadarka",
		"Kalecik Karasi",
		"Kékfrankos",
		"Kéknyelu",
		"Kerner",
		"Klevener",
		"Koshu",
		"Lagrein",
		"Lambrusco",
		"Lemberger",
		"Liliorila",
		"Loureiro",
		"Lendelel",
		"Maccabeu",
		"Madeleine Oberlin",
		"Malaga blanc",
		"Malbec",
		"Malvoisie",
		"Mammolo",
		"Manseng noir",
		"Marquette",
		"Marsanne",
		"Marselan",
		"Mauzac",
		"Mavro",
		"Mavrud",
		"Mècle",
		"Melon",
		"Melon de Bourgogne",
		"Merlot",
		"Merlot blanc",
		"Meslier Saint-François",
		"Meunier",
		"Milgranet",
		"Millot Léon",
		"Minnella",
		"Mireille",
		"Mollard",
		"Molette",
		"Molinara",
		"Monbadon",
		"Mondeuse",
		"Monerac",
		"Montepulciano",
		"Montils",
		"Moristel",
		"Morrastel",
		"Moscato",
		"Mourvèdre",
		"Müller-Thurgau",
		"Muscadelle",
		"Muscadet",
		"Muscardin",
		"Muscat à petits grains",
		"Muscat d'Alexandrie",
		"Muscat d'Espagne",
		"Muscat de Hambourg",
		"Muscat d'Italie",
		"Muscat noir",
		"Muscat ottonel",
		"Muscat romain",
		"Narince",
		"Nebbiolo",
		"Négrette",
		"Negroamaro",
		"Neheleschol",
		"Nerello Cappuccio",
		"Nerello mantellato",
		"Nerello mascalese",
		"Nerettia cuneese",
		"Neretto di Bairo",
		"Nero d'Avola",
		"Nielluccio",
		"Noir de Listan",
		"Nonay",
		"Noa",
		"Odjaleschi",
		"Okuzgozu",
		"Olivette blanche",
		"Olivette noire",
		"Ondenc",
		"Onchette",
		"Païen",
		"Palomino",
		"Pamid",
		"Parraleta",
		"Pascal blanc",
		"Pecorino",
		"Pedro Ximénez",
		"Pelara",
		"Peloursin",
		"Perdea",
		"Periquita",
		"Perle de Csaba",
		"Perlette",
		"Persan",
		"Petit Courbu",
		"Petit manseng",
		"Petit verdot",
		"Petit meslier",
		"Petite syrah",
		"Petite arvine",
		"Picardan",
		"Picolit",
		"Piquepoul noir",
		"Piquepoul gris",
		"Piquepoul blanc",
		"Pignatello",
		"Pignoletto",
		"Pineau d'Aunis",
		"Pinotage",
		"Pinot blanc",
		"Pinot gris",
		"Pinot lièbault",
		"Pinot meunier",
		"Pinot noir",
		"Plavac mali",
		"Pointu de vimines",
		"Poulsard",
		"Primitivo",
		"Prin blanc",
		"Prior noir",
		"Prosecco",
		"Prugnolo Gentile",
		"Prunelard",
		"Rayon d'or",
		"Rabo",
		"Refosco",
		"Regent",
		"Regina",
		"Reine des vignes",
		"Ribier",
		"Riesling",
		"Riesling italien",
		"Robin noir",
		"Rogettaz",
		"Rognin",
		"Rolle",
		"Romain",
		"Romorantin",
		"Rondinella",
		"Rouge de Diolly",
		"Roussanne",
		"Roussette",
		"Sabal kanskoï",
		"Sabrevois",
		"Saint-François",
		"Saint-Jacques",
		"Saint-Jeannet",
		"Saint Laurent",
		"Sagrantino",
		"Sangiovese",
		"Saperavi",
		"Sauvignon blanc",
		"Sauvignon",
		"Savagnin blanc",
		"Savagnin rose",
		"Scheurebe",
		"Schiava",
		"Sciacarello",
		"Sémillon",
		"Sercial",
		"Sérenèze de Voreppe",
		"Servanin",
		"Servant",
		"Seyval blanc",
		"Skadarka",
		"Steen",
		"Sultanine",
		"Sylvaner",
		"Syrah",
		"Tannat",
		"Téoulier",
		"Teinturier",
		"Tempranillo",
		"Teroldego",
		"Terret noir",
		"Tibouren",
		"Tocai",
		"Tokay",
		"Torrontés",
		"Touriga franca",
		"Touriga nacional",
		"Traminer",
		"Trebbiano bianco",
		"Trepat",
		"Tressalier",
		"Trousseau",
		"Ugni blanc",
		"Valensy noir",
		"Vandal-cliche",
		"Verdal",
		"Verdaou",
		"Verdanel",
		"Verdejo",
		"Verdelho",
		"Verdesse",
		"Verdicchio",
		"Vermentino",
		"Vernaccia",
		"Verpillin",
		"Vidal blanc",
		"Viognier",
		"Viura",
		"Vranac",
		"Weissburgunder",
		"Welschriesling",
		"Xynisteri",
		"Zalema",
		"Zibbibo",
		"Zinfandel",
		"Zweigelt"

	};
}
