package com.devilopers.guigeek.vins;

public class StaticData {

	public static final String[] appellations = new String[] {
		"Ajaccio",
		"Aloxe-corton",
		"Alsace",
		"Alsace Grand Cru",
		"Anjou",
		"Anjou-coteaux-de-la-loire",
		"Anjou Villages",
		"Anjou Villages Brissac",
		"Arbois",
		"Auxey-duresses",
		"Bandol",
		"Banyuls",
		"Banyuls Grand Cru",
		"Barsac",
		"BAtard-montrachet",
		"Beaujolais",
		"Beaujolais-villages",
		"Beaumes-de-venise",
		"Beaune",
		"Bellet",
		"Bergerac",
		"Bienvenues-b�tard-montrachet",
		"Blagny",
		"Blaye",
		"Bonnes-mares",
		"Bonnezeaux",
		"Bordeaux",
		"Bordeaux Sup�rieur",
		"Bourgogne",
		"Bourgogne Aligot�",
		"Coteaux-bourguignons",
		"Bourgogne Mousseux",
		"Bourgogne Passe-tout-grains",
		"Bourgueil",
		"Bouzeron",
		"Brouilly",
		"Bugey",
		"Buzet",
		"Cabard�s",
		"Cabernet D'Anjou",
		"Cabernet De Saumur",
		"Cadillac",
		"Cahors",
		"Canon-fronsac",
		"Cassis",
		"C�rons",
		"Chablis",
		"Chablis Grand Cru",
		"Chambertin",
		"Chambertin-clos-de-b�ze",
		"Chambolle-musigny",
		"Champagne",
		"Chapelle-chambertin",
		"Charlemagne",
		"Charmes-chambertin",
		"Chassagne-montrachet",
		"Ch�teau-chalon",
		"Ch�teau-grillet",
		"Ch�teaumeillant",
		"Ch�teauneuf-du-pape",
		"Ch�tillon-en-diois",
		"Ch�nas",
		"Chevalier-montrachet",
		"Cheverny",
		"Chinon",
		"Chiroubles",
		"Chorey-l�s-beaune",
		"Clairette De Bellegarde",
		"Clairette De Die",
		"Clairette Du Languedoc",
		"Clos-de-la-roche",
		"Clos-de-tart",
		"Clos-de-vougeot",
		"Clos-des-lambrays",
		"Clos-saint-denis",
		"Collioure",
		"Condrieu",
		"Corbi�res",
		"Corbi�res-boutenac",
		"Cornas",
		"Corse",
		"Corton",
		"Corton-charlemagne",
		"Costi�res-de-n�mes",
		"C�te-de-beaune",
		"C�te-de-beaune-villages",
		"C�te-de-nuits-villages",
		"C�te-de-brouilly",
		"C�te-roannaise",
		"C�te-r�tie",
		"Coteaux-champenois",
		"Coteaux-d'aix-en-provence",
		"Coteaux-de-die",
		"Coteaux-de-l'aubance",
		"Coteaux-de-saumur",
		"Coteaux-du-giennois",
		"Coteaux-du-layon",
		"Coteaux-du-loir",
		"Coteaux-du-lyonnais",
		"Coteaux-du-vend�mois",
		"Coteaux-varois-en-provence",
		"C�tes-de-bergerac",
		"C�tes-de-blaye",
		"C�tes-de-bordeaux",
		"C�tes-de-bordeaux-saint-macaire",
		"C�tes-de-bourg",
		"C�tes-de-duras",
		"C�tes-de-montravel",
		"C�tes-de-provence",
		"C�tes-de-toul",
		"C�tes-du-forez",
		"C�tes-du-jura",
		"C�tes-du-marmandais",
		"C�tes-du-rh�ne",
		"C�tes-du-rh�ne Villages",
		"C�tes-du-roussillon",
		"C�tes-du-roussillon Villages",
		"C�tes-du-vivarais",
		"Cour-cheverny",
		"Cr�mant D'Alsace",
		"Cr�mant De Bordeaux",
		"Cr�mant De Bourgogne",
		"Cr�mant De Die",
		"Cr�mant De Limoux",
		"Cr�mant De Loire",
		"Cr�mant Du Jura",
		"Criots-b�tard-montrachet",
		"Crozes-hermitage",
		"�chezeaux",
		"Entre-deux-mers",
		"Faug�res",
		"Fiefs-vend�ens",
		"Fitou",
		"Fixin",
		"Fleurie",
		"Fronsac",
		"Fronton",
		"Gaillac",
		"Gaillac-premi�res-c�tes",
		"Gevrey-chambertin",
		"Gigondas",
		"Givry",
		"Grands-�chezeaux",
		"Graves",
		"Graves-de-vayres",
		"Graves-sup�rieures",
		"Grignan-les-adh�mar",
		"Griotte-chambertin",
		"Haut-m�doc",
		"Haut-montravel",
		"Haut-poitou",
		"Hermitage",
		"Irancy",
		"Iroul�guy",
		"Jasni�res",
		"Juli�nas",
		"Juran�on",
		"L'�toile",
		"La-grande-rue",
		"La-roman�e",
		"La-t�che",
		"Ladoix",
		"Lalande-de-pomerol",
		"Languedoc",
		"Latrici�res-chambertin",
		"Les-baux-de-provence",
		"Limoux",
		"Lirac",
		"Listrac-m�doc",
		"Loupiac",
		"Luberon",
		"Lussac-saint-�milion",
		"M�con",
		"Madiran",
		"Malep�re",
		"Maranges",
		"Marcillac",
		"Margaux",
		"Marsannay",
		"Maury",
		"Mazis-chambertin",
		"Mazoy�res-chambertin",
		"M�doc",
		"Menetou-salon",
		"Mercurey",
		"Meursault",
		"Minervois",
		"Minervois-la-livini�re",
		"Monbazillac",
		"Montagne-saint-�milion",
		"Montagny",
		"Month�lie",
		"Montlouis-sur-loire",
		"Montrachet",
		"Montravel",
		"Morey-saint-denis",
		"Morgon",
		"Moselle",
		"Moulin-�-vent",
		"Moulis",
		"Muscadet",
		"Muscadet-coteaux-de-la-loire",
		"Muscadet-c�tes-de-grandlieu",
		"Muscadet-s�vre-et-maine",
		"Muscat De Beaumes-de-Venise",
		"Muscat De Frontignan",
		"Muscat De Lunel",
		"Muscat De Mireval",
		"Muscat De Rivesaltes",
		"Muscat De Saint-Jean-de-Minervois",
		"Muscat Du Cap-Corse",
		"Musigny",
		"N�ac",
		"Nuits-saint-georges",
		"Orl�ans",
		"Orl�ans-cl�ry",
		"Pacherenc-du-vic-bilh",
		"Palette",
		"Patrimonio",
		"Pauillac",
		"P�charmant",
		"Pernand-vergelesses",
		"Pessac-l�ognan",
		"Petit-chablis",
		"Pierrevert",
		"Pomerol",
		"Pommard",
		"Pouilly-fuiss�",
		"Pouilly-fum�",
		"Pouilly-loch�",
		"Pouilly-sur-loire",
		"Pouilly-vinzelles",
		"Premi�res-c�tes-de-bordeaux",
		"Puisseguin-saint-�milion",
		"Puligny-montrachet",
		"Quarts-de-chaume",
		"Quincy",
		"Rasteau",
		"R�gni�",
		"Reuilly",
		"Richebourg",
		"Rivesaltes",
		"Roman�e-conti",
		"Roman�e-saint-vivant",
		"Ros� D'Anjou",
		"Ros� De Loire",
		"Ros� Des Riceys",
		"Rosette",
		"Roussette De Savoie",
		"Roussette Du Bugey",
		"Ruchottes-chambertin",
		"Rully",
		"Saint-amour",
		"Saint-aubin",
		"Saint-bris",
		"Saint-chinian",
		"Saint-�milion",
		"Saint-�milion Grand Cru",
		"Saint-est�phe",
		"Saint-georges-saint-�milion",
		"Saint-joseph",
		"Saint-julien",
		"Saint-nicolas-de-bourgueil",
		"Saint-p�ray",
		"Saint-pour�ain",
		"Saint-romain",
		"Saint-v�ran",
		"Sainte-croix-du-mont",
		"Sainte-foy-bordeaux",
		"Sancerre",
		"Santenay",
		"Saumur",
		"Saumur-champigny",
		"Saussignac",
		"Sauternes",
		"Savenni�res",
		"Savigny-l�s-beaune",
		"Seyssel",
		"Tavel",
		"Touraine",
		"Touraine-noble-jou�",
		"Vacqueyras",
		"Valen�ay",
		"Ventoux",
		"Vin De Savoie",
		"Vinsobres",
		"Vir�-cless�",
		"Volnay",
		"Vosne-roman�e",
		"Vougeot",
		"Vouvray"
	};
	
	
	public static final String[] cepages = new String[] {
		"Abondant",
		"Abouriou",
		"Admirable de Courtiller",
		"Aglianico",
		"Air�n",
		"Albana",
		"Albari�o",
		"Aleatico",
		"Alicante-henri-bouschet",
		"Aligot�",
		"Alphonse-lavall�e",
		"Altesse",
		"Amigne",
		"Angevine Oberlin",
		"Aramon",
		"Aranel",
		"Arbane",
		"Arbois",
		"Arinarnoa",
		"Arinto",
		"Arriloba",
		"Arrouya",
		"Arvine",
		"Arrufiac",
		"Auxerrois",
		"Baco",
		"Baga",
		"Balochin",
		"Barbaroux",
		"Barbera",
		"Baroque",
		"Bergeron",
		"Bia",
		"Black Hamburg",
		"Blanc Verdan",
		"Bleu de Franconie",
		"Bogazkere",
		"Bombino",
		"Bonarda",
		"Bovale",
		"Bouchet",
		"Bourboulenc",
		"Brachetto",
		"Brunello",
		"Bual",
		"Bezoul el khadem",
		"Cabernet",
		"Cabernet franc",
		"Cabernet-sauvignon",
		"Canaiolo",
		"Cannonau",
		"Carcajolo blanc",
		"Carcajolo noir",
		"Cardinal",
		"Carignan ",
		"Carm�n�re",
		"Carricante",
		"Castellaro",
		"Catarratto",
		"C�sar",
		"Chambourcin",
		"Chancellor",
		"Chardonnay",
		"Chasselas",
		"Chasselas de J�rusalem",
		"Chasselas de Moissac",
		"Chasselas de Thomery",
		"Chatus",
		"Chelois",
		"Chenin",
		"Ciliegiolo",
		"Cinsault",
		"Clairette",
		"Claverie",
		"Clinton",
		"Colombard",
		"Colorino",
		"Corb�se",
		"Cornalin",
		"Cortese",
		"Corvina",
		"C�t",
		"Counoise",
		"Couston",
		"Croatina",
		"Crussin",
		"Czabah",
		"Dabouki",
		"Danube",
		"Dattier de Beyrouth",
		"Dindarella",
		"Diolinoir",
		"Divico",
		"Dobricic",
		"Dolcetto",
		"Donnery",
		"Doukkala",
		"Duras",
		"Durif",
		"Elbling",
		"Emir",
		"Ermitage",
		"�traire de la Dui",
		"Falanghina",
		"Fendant",
		"Fer Servadou",
		"Feteasca",
		"Fiano",
		"Folle-Blanche",
		"Fragolino",
		"Frankenthal",
		"Frankonia",
		"Frappato di Vittoria",
		"Frankovka",
		"Freisa",
		"Friulano",
		"Frontenac",
		"Furmint",
		"Fumin",
		"Gaglioppo",
		"Gamaret",
		"Gamay",
		"Gamay de Bouze",
		"Gamay de Chaudenay",
		"Gamay Fr�aux",
		"Gamza",
		"Ganson",
		"Garganega",
		"Garanoir",
		"Gascon",
		"Genovese",
		"Gewurztraminer",
		"Goldriesling",
		"Gouais",
		"Gouget",
		"Graisse",
		"Gramon",
		"Grassen",
		"Grechetto",
		"Greco",
		"Grenache",
		"Gringet",
		"Grignolino",
		"Grolleau",
		"Groppello bianco",
		"Groppello gentile",
		"Groppello di Mocasina",
		"Groppello di Santo Stefano",
		"Gros colman",
		"Gros manseng",
		"Gros noir des B�ni-Abb�s",
		"Gros vert",
		"Gutedel",
		"Gr�ner Veltliner",
		"H�rslevel�",
		"Hibou",
		"Humagne blanche",
		"Humagne rouge",
		"Id�al",
		"Inzolia",
		"Isabelle",
		"Italia",
		"Jacqu�re",
		"Jacquez",
		"Jaoumet",
		"Johannisberg",
		"Joubertin",
		"Kadarka",
		"Kalecik Karasi",
		"K�kfrankos",
		"K�knyelu",
		"Kerner",
		"Klevener",
		"Koshu",
		"Lagrein",
		"Lambrusco",
		"Lemberger",
		"Liliorila",
		"Loureiro",
		"Lendelel",
		"Maccabeu",
		"Madeleine Oberlin",
		"Malaga blanc",
		"Malbec",
		"Malvoisie",
		"Mammolo",
		"Manseng noir",
		"Marquette",
		"Marsanne",
		"Marselan",
		"Mauzac",
		"Mavro",
		"Mavrud",
		"M�cle",
		"Melon",
		"Melon de Bourgogne",
		"Merlot",
		"Merlot blanc",
		"Meslier Saint-Fran�ois",
		"Meunier",
		"Milgranet",
		"Millot L�on",
		"Minnella",
		"Mireille",
		"Mollard",
		"Molette",
		"Molinara",
		"Monbadon",
		"Mondeuse",
		"Monerac",
		"Montepulciano",
		"Montils",
		"Moristel",
		"Morrastel",
		"Moscato",
		"Mourv�dre",
		"M�ller-Thurgau",
		"Muscadelle",
		"Muscadet",
		"Muscardin",
		"Muscat � petits grains",
		"Muscat d'Alexandrie",
		"Muscat d'Espagne",
		"Muscat de Hambourg",
		"Muscat d'Italie",
		"Muscat noir",
		"Muscat ottonel",
		"Muscat romain",
		"Narince",
		"Nebbiolo",
		"N�grette",
		"Negroamaro",
		"Neheleschol",
		"Nerello Cappuccio",
		"Nerello mantellato",
		"Nerello mascalese",
		"Nerettia cuneese",
		"Neretto di Bairo",
		"Nero d'Avola",
		"Nielluccio",
		"Noir de Listan",
		"Nonay",
		"Noa",
		"Odjaleschi",
		"Okuzgozu",
		"Olivette blanche",
		"Olivette noire",
		"Ondenc",
		"Onchette",
		"Pa�en",
		"Palomino",
		"Pamid",
		"Parraleta",
		"Pascal blanc",
		"Pecorino",
		"Pedro Xim�nez",
		"Pelara",
		"Peloursin",
		"Perdea",
		"Periquita",
		"Perle de Csaba",
		"Perlette",
		"Persan",
		"Petit Courbu",
		"Petit manseng",
		"Petit verdot",
		"Petit meslier",
		"Petite syrah",
		"Petite arvine",
		"Picardan",
		"Picolit",
		"Piquepoul noir",
		"Piquepoul gris",
		"Piquepoul blanc",
		"Pignatello",
		"Pignoletto",
		"Pineau d'Aunis",
		"Pinotage",
		"Pinot blanc",
		"Pinot gris",
		"Pinot li�bault",
		"Pinot meunier",
		"Pinot noir",
		"Plavac mali",
		"Pointu de vimines",
		"Poulsard",
		"Primitivo",
		"Prin blanc",
		"Prior noir",
		"Prosecco",
		"Prugnolo Gentile",
		"Prunelard",
		"Rayon d'or",
		"Rabo",
		"Refosco",
		"Regent",
		"Regina",
		"Reine des vignes",
		"Ribier",
		"Riesling",
		"Riesling italien",
		"Robin noir",
		"Rogettaz",
		"Rognin",
		"Rolle",
		"Romain",
		"Romorantin",
		"Rondinella",
		"Rouge de Diolly",
		"Roussanne",
		"Roussette",
		"Sabal kansko�",
		"Sabrevois",
		"Saint-Fran�ois",
		"Saint-Jacques",
		"Saint-Jeannet",
		"Saint Laurent",
		"Sagrantino",
		"Sangiovese",
		"Saperavi",
		"Sauvignon blanc",
		"Sauvignon",
		"Savagnin blanc",
		"Savagnin rose",
		"Scheurebe",
		"Schiava",
		"Sciacarello",
		"S�millon",
		"Sercial",
		"S�ren�ze de Voreppe",
		"Servanin",
		"Servant",
		"Seyval blanc",
		"Skadarka",
		"Steen",
		"Sultanine",
		"Sylvaner",
		"Syrah",
		"Tannat",
		"T�oulier",
		"Teinturier",
		"Tempranillo",
		"Teroldego",
		"Terret noir",
		"Tibouren",
		"Tocai",
		"Tokay",
		"Torront�s",
		"Touriga franca",
		"Touriga nacional",
		"Traminer",
		"Trebbiano bianco",
		"Trepat",
		"Tressalier",
		"Trousseau",
		"Ugni blanc",
		"Valensy noir",
		"Vandal-cliche",
		"Verdal",
		"Verdaou",
		"Verdanel",
		"Verdejo",
		"Verdelho",
		"Verdesse",
		"Verdicchio",
		"Vermentino",
		"Vernaccia",
		"Verpillin",
		"Vidal blanc",
		"Viognier",
		"Viura",
		"Vranac",
		"Weissburgunder",
		"Welschriesling",
		"Xynisteri",
		"Zalema",
		"Zibbibo",
		"Zinfandel",
		"Zweigelt"

	};
}
